In [114]:
import pandas as pd
import numpy as np

In [115]:
playerset = pd.read_csv("male_players (legacy).csv")

C:\Program Files\KMSpico\temp\ipykernel_27668\1813319767.py:1: DtypeWarning: Columns (108) have mixed types. Specify dtype option on import or set low_memory=False.
  playerset = pd.read_csv("male_players (legacy).csv")

In [116]:
#extracting necessary columns
needed = playerset[['overall','potential','wage_eur','age','height_cm','weight_kg','weak_foot','skill_moves','international_reputation','pace','shooting','passing','dribbling','defending','physic','attacking_crossing','attacking_finishing','attacking_heading_accuracy','attacking_short_passing','attacking_volleys','skill_dribbling','skill_curve','skill_fk_accuracy','skill_long_passing','skill_ball_control','movement_acceleration','movement_sprint_speed','movement_agility','movement_reactions','movement_balance','power_shot_power','power_jumping','power_stamina','power_strength','power_long_shots','mentality_positioning','mentality_vision','mentality_penalties','mentality_composure','defending_marking_awareness','defending_standing_tackle','defending_sliding_tackle','goalkeeping_diving','goalkeeping_handling','goalkeeping_kicking','goalkeeping_positioning','goalkeeping_reflexes','goalkeeping_speed','ls','st','rs','lw','lf','cf','rf','rw','lam','cam','ram','lm','lcm','cm','rcm','rm','lwb','ldm','cdm','rdm','rwb','lb','lcb','cb','rcb','rb','gk']]

In [117]:
needed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161583 entries, 0 to 161582
Data columns (total 75 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   overall                      161583 non-null  int64
 1   potential                    161583 non-null  int64
 2   wage_eur                     159822 non-null  float64
 3   age                          161583 non-null  int64
 4   height_cm                    161583 non-null  int64
 5   weight_kg                    161583 non-null  int64
 6   weak_foot                    161583 non-null  int64
 7   skill_moves                  161583 non-null  int64
 8   international_reputation     161583 non-null  int64
 9   pace                         143614 non-null  float64
 10  shooting                     143614 non-null  float64
 11  passing                      143614 non-null  float64
 12  dribbling                    143614 non-null  float64
 13  defending                    143614 non-null  float64
 14  physic                       143614 non-null  float64
 15  attacking_crossing           161583 non-null  int64
 16  attacking_finishing          161583 non-null  int64
 17  attacking_heading_accuracy   161583 non-null  int64
 18  attacking_short_passing      161583 non-null  int64
 19  attacking_volleys            161583 non-null  int64
 20  skill_dribbling              161583 non-null  int64
 21  skill_curve                  161583 non-null  int64
 22  skill_fk_accuracy            161583 non-null  int64
 23  skill_long_passing           161583 non-null  int64
 24  skill_ball_control           161583 non-null  int64
 25  movement_acceleration        161583 non-null  int64
 26  movement_sprint_speed        161583 non-null  int64
 27  movement_agility             161583 non-null  int64
 28  movement_reactions           161583 non-null  int64
 29  movement_balance             161583 non-null  int64
 30  power_shot_power             161583 non-null  int64
 31  power_jumping                161583 non-null  int64
 32  power_stamina                161583 non-null  int64
 33  power_strength               161583 non-null  int64
 34  power_long_shots             161583 non-null  int64
 35  mentality_positioning        161583 non-null  int64
 36  mentality_vision             161583 non-null  int64
 37  mentality_penalties          161583 non-null  int64
 38  mentality_composure          128722 non-null  float64
 39  defending_marking_awareness  161583 non-null  int64
 40  defending_standing_tackle    161583 non-null  int64
 41  defending_sliding_tackle     161583 non-null  int64
 42  goalkeeping_diving           161583 non-null  int64
 43  goalkeeping_handling         161583 non-null  int64
 44  goalkeeping_kicking          161583 non-null  int64
 45  goalkeeping_positioning      161583 non-null  int64
 46  goalkeeping_reflexes         161583 non-null  int64
 47  goalkeeping_speed            17969 non-null   float64
 48  ls                           161583 non-null  object
 49  st                           161583 non-null  object
 50  rs                           161583 non-null  object
 51  lw                           161583 non-null  object
 52  lf                           161583 non-null  object
 53  cf                           161583 non-null  object
 54  rf                           161583 non-null  object
 55  rw                           161583 non-null  object
 56  lam                          161583 non-null  object
 57  cam                          161583 non-null  object
 58  ram                          161583 non-null  object
 59  lm                           161583 non-null  object
 60  lcm                          161583 non-null  object
 61  cm                           161583 non-null  object
 62  rcm                          161583 non-null  object
 63  rm                           161583 non-null  object
 64  lwb                          161583 non-null  object
 65  ldm                          161583 non-null  object
 66  cdm                          161583 non-null  object
 67  rdm                          161583 non-null  object
 68  rwb                          161583 non-null  object
 69  lb                           161583 non-null  object
 70  lcb                          161583 non-null  object
 71  cb                           161583 non-null  object
 72  rcb                          161583 non-null  object
 73  rb                           161583 non-null  object
 74  gk                           161583 non-null  object
dtypes: float64(9), int64(39), object(27)
memory usage: 92.5+ MB

## Extracting delimitered columns

### Position ratings

In [120]:
poststats = needed.iloc[:,-27:]
display(poststats)
posrats = poststats.columns.to_list()

,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,89+3,89+3,89+3,92+3,90+3,90+3,90+3,92+3,92+3,92+3,...,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3
1,91+1,91+1,91+1,89+3,91+1,91+1,91+1,89+3,89+3,89+3,...,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3
2,84+3,84+3,84+3,88+2,87+3,87+3,87+3,88+2,88+2,88+2,...,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3
3,87+3,87+3,87+3,84+3,86+3,86+3,86+3,84+3,86+3,86+3,...,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3
4,38+3,38+3,38+3,36+3,37+3,37+3,37+3,36+3,36+3,36+3,...,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161578,47+2,47+2,47+2,46,46,46,46,46,44+2,44+2,...,32+2,32+2,32+2,37+2,36+2,31+2,31+2,31+2,36+2,14+2
161579,35+2,35+2,35+2,34,33,33,33,34,32+2,32+2,...,41+2,41+2,41+2,43+2,44+2,48+2,48+2,48+2,44+2,15+2
161580,46+2,46+2,46+2,46,46,46,46,46,45+2,45+2,...,45+2,45+2,45+2,47+2,47+2,46+2,46+2,46+2,47+2,14+2
161581,47+2,47+2,47+2,46,46,46,46,46,45+2,45+2,...,30+2,30+2,30+2,34+2,32+2,28+2,28+2,28+2,32+2,15+2
161582,32+2,32+2,32+2,31,30,30,30,31,30+2,30+2,...,40+2,40+2,40+2,39+2,41+2,46+2,46+2,46+2,41+2,13+2

In [121]:
cols = dict()

In [122]:
for thiscol in poststats.columns:
    posistat = poststats[thiscol].str.split('+',expand=True)
    posistat.fillna(0,inplace=True)
    posistat = posistat.apply(pd.to_numeric,errors='coerce')
    cols[thiscol] = posistat.sum(axis=1)

In [123]:
coldf = pd.DataFrame(cols)
display(coldf)

,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,92.0,92.0,92.0,95.0,93.0,93.0,93.0,95.0,95.0,95.0,...,65.0,65.0,65.0,65.0,57.0,48.0,48.0,48.0,57.0,18
1,92.0,92.0,92.0,92.0,92.0,92.0,92.0,92.0,92.0,92.0,...,66.0,66.0,66.0,66.0,60.0,55.0,55.0,55.0,60.0,19
2,87.0,87.0,87.0,90.0,90.0,90.0,90.0,90.0,90.0,90.0,...,67.0,67.0,67.0,67.0,58.0,49.0,49.0,49.0,58.0,17
3,90.0,90.0,90.0,87.0,89.0,89.0,89.0,87.0,89.0,89.0,...,68.0,68.0,68.0,64.0,59.0,58.0,58.0,58.0,59.0,20
4,41.0,41.0,41.0,39.0,40.0,40.0,40.0,39.0,39.0,39.0,...,43.0,43.0,43.0,39.0,39.0,41.0,41.0,41.0,39.0,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161578,49.0,49.0,49.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0,...,34.0,34.0,34.0,39.0,38.0,33.0,33.0,33.0,38.0,16
161579,37.0,37.0,37.0,34.0,33.0,33.0,33.0,34.0,34.0,34.0,...,43.0,43.0,43.0,45.0,46.0,50.0,50.0,50.0,46.0,17
161580,48.0,48.0,48.0,46.0,46.0,46.0,46.0,46.0,47.0,47.0,...,47.0,47.0,47.0,49.0,49.0,48.0,48.0,48.0,49.0,16
161581,49.0,49.0,49.0,46.0,46.0,46.0,46.0,46.0,47.0,47.0,...,32.0,32.0,32.0,36.0,34.0,30.0,30.0,30.0,34.0,17
161582,34.0,34.0,34.0,31.0,30.0,30.0,30.0,31.0,32.0,32.0,...,42.0,42.0,42.0,41.0,43.0,48.0,48.0,48.0,43.0,15

In [124]:
needed.drop(columns = needed.iloc[:,-27:], inplace = True)
needed=pd.concat([needed,coldf], axis=1)
display(needed)

C:\Program Files\KMSpico\temp\ipykernel_27668\3743406020.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  needed.drop(columns = needed.iloc[:,-27:], inplace = True)

,overall,potential,wage_eur,age,height_cm,weight_kg,weak_foot,skill_moves,international_reputation,pace,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,93,95,550000.0,27,169,67,3,4,5,93.0,...,65.0,65.0,65.0,65.0,57.0,48.0,48.0,48.0,57.0,18
1,92,92,375000.0,29,185,80,4,5,5,93.0,...,66.0,66.0,66.0,66.0,60.0,55.0,55.0,55.0,60.0,19
2,90,90,275000.0,30,180,80,2,4,5,93.0,...,67.0,67.0,67.0,67.0,58.0,49.0,49.0,49.0,58.0,17
3,90,90,275000.0,32,195,95,4,4,5,76.0,...,68.0,68.0,68.0,64.0,59.0,58.0,58.0,58.0,59.0,20
4,90,90,300000.0,28,193,92,4,1,5,NaN,...,43.0,43.0,43.0,39.0,39.0,41.0,41.0,41.0,39.0,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161578,46,61,700.0,18,180,73,3,2,1,63.0,...,34.0,34.0,34.0,39.0,38.0,33.0,33.0,33.0,38.0,16
161579,46,58,750.0,19,188,83,3,2,1,55.0,...,43.0,43.0,43.0,45.0,46.0,50.0,50.0,50.0,46.0,17
161580,46,58,500.0,19,181,73,2,2,1,65.0,...,47.0,47.0,47.0,49.0,49.0,48.0,48.0,48.0,49.0,16
161581,46,70,500.0,17,175,68,3,2,1,55.0,...,32.0,32.0,32.0,36.0,34.0,30.0,30.0,30.0,34.0,17
161582,46,63,500.0,17,180,70,3,2,1,61.0,...,42.0,42.0,42.0,41.0,43.0,48.0,48.0,48.0,43.0,15

In [125]:
needed.rename(columns={0:'numpos'},inplace=True)

In [126]:
needed.info(show_counts=True, verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161583 entries, 0 to 161582
Data columns (total 75 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   overall                      161583 non-null  int64
 1   potential                    161583 non-null  int64
 2   wage_eur                     159822 non-null  float64
 3   age                          161583 non-null  int64
 4   height_cm                    161583 non-null  int64
 5   weight_kg                    161583 non-null  int64
 6   weak_foot                    161583 non-null  int64
 7   skill_moves                  161583 non-null  int64
 8   international_reputation     161583 non-null  int64
 9   pace                         143614 non-null  float64
 10  shooting                     143614 non-null  float64
 11  passing                      143614 non-null  float64
 12  dribbling                    143614 non-null  float64
 13  defending                    143614 non-null  float64
 14  physic                       143614 non-null  float64
 15  attacking_crossing           161583 non-null  int64
 16  attacking_finishing          161583 non-null  int64
 17  attacking_heading_accuracy   161583 non-null  int64
 18  attacking_short_passing      161583 non-null  int64
 19  attacking_volleys            161583 non-null  int64
 20  skill_dribbling              161583 non-null  int64
 21  skill_curve                  161583 non-null  int64
 22  skill_fk_accuracy            161583 non-null  int64
 23  skill_long_passing           161583 non-null  int64
 24  skill_ball_control           161583 non-null  int64
 25  movement_acceleration        161583 non-null  int64
 26  movement_sprint_speed        161583 non-null  int64
 27  movement_agility             161583 non-null  int64
 28  movement_reactions           161583 non-null  int64
 29  movement_balance             161583 non-null  int64
 30  power_shot_power             161583 non-null  int64
 31  power_jumping                161583 non-null  int64
 32  power_stamina                161583 non-null  int64
 33  power_strength               161583 non-null  int64
 34  power_long_shots             161583 non-null  int64
 35  mentality_positioning        161583 non-null  int64
 36  mentality_vision             161583 non-null  int64
 37  mentality_penalties          161583 non-null  int64
 38  mentality_composure          128722 non-null  float64
 39  defending_marking_awareness  161583 non-null  int64
 40  defending_standing_tackle    161583 non-null  int64
 41  defending_sliding_tackle     161583 non-null  int64
 42  goalkeeping_diving           161583 non-null  int64
 43  goalkeeping_handling         161583 non-null  int64
 44  goalkeeping_kicking          161583 non-null  int64
 45  goalkeeping_positioning      161583 non-null  int64
 46  goalkeeping_reflexes         161583 non-null  int64
 47  goalkeeping_speed            17969 non-null   float64
 48  ls                           161583 non-null  float64
 49  st                           161583 non-null  float64
 50  rs                           161583 non-null  float64
 51  lw                           161583 non-null  float64
 52  lf                           161583 non-null  float64
 53  cf                           161583 non-null  float64
 54  rf                           161583 non-null  float64
 55  rw                           161583 non-null  float64
 56  lam                          161583 non-null  float64
 57  cam                          161583 non-null  float64
 58  ram                          161583 non-null  float64
 59  lm                           161583 non-null  float64
 60  lcm                          161583 non-null  float64
 61  cm                           161583 non-null  float64
 62  rcm                          161583 non-null  float64
 63  rm                           161583 non-null  float64
 64  lwb                          161583 non-null  float64
 65  ldm                          161583 non-null  float64
 66  cdm                          161583 non-null  float64
 67  rdm                          161583 non-null  float64
 68  rwb                          161583 non-null  float64
 69  lb                           161583 non-null  float64
 70  lcb                          161583 non-null  float64
 71  cb                           161583 non-null  float64
 72  rcb                          161583 non-null  float64
 73  rb                           161583 non-null  float64
 74  gk                           161583 non-null  int64
dtypes: float64(35), int64(40)
memory usage: 92.5 MB

## Defining preprocessing function (for encoding and imputation)

In [128]:
def preprocessor(dataframe):
    df = dataframe.copy()
    #thresholding
    threshold = round(0.6*len(df))
    df.dropna(axis=1,thresh=threshold, inplace=True)
    df.dropna(axis=0,thresh = 0.9*df.shape[0], inplace=True)

    #importing necessary libraries
    from sklearn.preprocessing import OneHotEncoder
    encoder = OneHotEncoder()

    from sklearn.experimental import enable_iterative_imputer
    from sklearn.impute import IterativeImputer
    imp = IterativeImputer(max_iter=10,random_state=42)

    #splitting data into categorical and numeric for encoding and imputation
    numcols=dataframe.select_dtypes(include='number').columns.tolist()
    catcols = dataframe.select_dtypes(exclude='number').columns.tolist()
    
    #encoding categorical data
    if len(catcols)!=0:
        encoded = encoder.fit_transform(dataframe[catcols])
        encoded_df = pd.DataFrame(encoded)
    else:
        encoded_df = pd.DataFrame()

    numeric_df = dataframe[numcols]
    num_filled = pd.DataFrame(np.round(imp.fit_transform(numeric_df)),columns=numeric_df.columns)

    processed_df = pd.concat([encoded_df,num_filled],axis=1)

    return(processed_df)

In [129]:
playerdata = preprocessor(needed)

C:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\impute\_iterative.py:825: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [130]:
playerinfo=playerdata.copy()

In [131]:
playerinfo.info(verbose = True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161583 entries, 0 to 161582
Data columns (total 75 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   overall                      161583 non-null  float64
 1   potential                    161583 non-null  float64
 2   wage_eur                     161583 non-null  float64
 3   age                          161583 non-null  float64
 4   height_cm                    161583 non-null  float64
 5   weight_kg                    161583 non-null  float64
 6   weak_foot                    161583 non-null  float64
 7   skill_moves                  161583 non-null  float64
 8   international_reputation     161583 non-null  float64
 9   pace                         161583 non-null  float64
 10  shooting                     161583 non-null  float64
 11  passing                      161583 non-null  float64
 12  dribbling                    161583 non-null  float64
 13  defending                    161583 non-null  float64
 14  physic                       161583 non-null  float64
 15  attacking_crossing           161583 non-null  float64
 16  attacking_finishing          161583 non-null  float64
 17  attacking_heading_accuracy   161583 non-null  float64
 18  attacking_short_passing      161583 non-null  float64
 19  attacking_volleys            161583 non-null  float64
 20  skill_dribbling              161583 non-null  float64
 21  skill_curve                  161583 non-null  float64
 22  skill_fk_accuracy            161583 non-null  float64
 23  skill_long_passing           161583 non-null  float64
 24  skill_ball_control           161583 non-null  float64
 25  movement_acceleration        161583 non-null  float64
 26  movement_sprint_speed        161583 non-null  float64
 27  movement_agility             161583 non-null  float64
 28  movement_reactions           161583 non-null  float64
 29  movement_balance             161583 non-null  float64
 30  power_shot_power             161583 non-null  float64
 31  power_jumping                161583 non-null  float64
 32  power_stamina                161583 non-null  float64
 33  power_strength               161583 non-null  float64
 34  power_long_shots             161583 non-null  float64
 35  mentality_positioning        161583 non-null  float64
 36  mentality_vision             161583 non-null  float64
 37  mentality_penalties          161583 non-null  float64
 38  mentality_composure          161583 non-null  float64
 39  defending_marking_awareness  161583 non-null  float64
 40  defending_standing_tackle    161583 non-null  float64
 41  defending_sliding_tackle     161583 non-null  float64
 42  goalkeeping_diving           161583 non-null  float64
 43  goalkeeping_handling         161583 non-null  float64
 44  goalkeeping_kicking          161583 non-null  float64
 45  goalkeeping_positioning      161583 non-null  float64
 46  goalkeeping_reflexes         161583 non-null  float64
 47  goalkeeping_speed            161583 non-null  float64
 48  ls                           161583 non-null  float64
 49  st                           161583 non-null  float64
 50  rs                           161583 non-null  float64
 51  lw                           161583 non-null  float64
 52  lf                           161583 non-null  float64
 53  cf                           161583 non-null  float64
 54  rf                           161583 non-null  float64
 55  rw                           161583 non-null  float64
 56  lam                          161583 non-null  float64
 57  cam                          161583 non-null  float64
 58  ram                          161583 non-null  float64
 59  lm                           161583 non-null  float64
 60  lcm                          161583 non-null  float64
 61  cm                           161583 non-null  float64
 62  rcm                          161583 non-null  float64
 63  rm                           161583 non-null  float64
 64  lwb                          161583 non-null  float64
 65  ldm                          161583 non-null  float64
 66  cdm                          161583 non-null  float64
 67  rdm                          161583 non-null  float64
 68  rwb                          161583 non-null  float64
 69  lb                           161583 non-null  float64
 70  lcb                          161583 non-null  float64
 71  cb                           161583 non-null  float64
 72  rcb                          161583 non-null  float64
 73  rb                           161583 non-null  float64
 74  gk                           161583 non-null  float64
dtypes: float64(75)
memory usage: 92.5 MB

### Creating relevant subsets

In [133]:
#averaging the skill for the skills column
attacking = playerinfo.loc[:,playerinfo.columns.str.startswith('attacking')].mean(axis=1).tolist()
skill =  playerinfo.loc[:,playerinfo.columns.str.startswith('skill')].mean(axis=1).tolist()
movement =  playerinfo.loc[:,playerinfo.columns.str.startswith('movement')].mean(axis=1).tolist()
power =  playerinfo.loc[:,playerinfo.columns.str.startswith('power')].mean(axis=1).tolist()
mentality =  playerinfo.loc[:,playerinfo.columns.str.startswith('mentality')].mean(axis=1).tolist()
defendingg =  playerinfo.loc[:,playerinfo.columns.str.startswith('defending_')].mean(axis=1).tolist()
goalkeeping =  playerinfo.loc[:,playerinfo.columns.str.startswith('goalkeeping')].mean(axis=1).tolist()

weight_to_height = playerinfo['weight_kg']/playerinfo['height_cm']

In [134]:
modified = playerinfo.loc[:,playerinfo.columns.str.startswith('attacking')].columns.tolist()+playerinfo.loc[:,playerinfo.columns.str.startswith('skill')].columns.tolist()+playerinfo.loc[:,playerinfo.columns.str.startswith('movement')].columns.tolist()+playerinfo.loc[:,playerinfo.columns.str.startswith('power')].columns.tolist()+playerinfo.loc[:,playerinfo.columns.str.startswith('mentality')].columns.tolist()+playerinfo.loc[:,playerinfo.columns.str.startswith('defending_')].columns.tolist()+playerinfo.loc[:,playerinfo.columns.str.startswith('goalkeeping')].columns.tolist()
print(modified)

['attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_moves', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed']

In [135]:
skills = [attacking,skill,movement,power,mentality,defendingg,goalkeeping]
colus = ['attacking','skill','movement','power','mentality','defendingg','goalkeeping']
averagedskills=pd.DataFrame([attacking,skill,movement,power,mentality,defendingg,goalkeeping],index = colus).T
display(averagedskills)

,attacking,skill,movement,power,mentality,defendingg,goalkeeping
0,84.6,75.166667,93.8,75.6,86.50,22.000000,24.333333
1,86.6,71.500000,86.2,89.8,86.75,25.333333,24.833333
2,77.4,71.833333,91.8,76.0,85.00,27.000000,23.500000
3,83.8,69.666667,72.6,84.8,87.50,31.000000,22.333333
4,28.4,24.666667,57.2,54.4,36.25,25.000000,83.333333
...,...,...,...,...,...,...,...
161578,42.8,33.500000,57.2,46.0,44.00,23.000000,19.166667
161579,29.2,23.166667,49.0,46.2,32.00,48.666667,18.000000
161580,40.4,31.500000,60.6,48.2,41.25,43.666667,18.333333
161581,41.4,29.666667,54.6,50.2,48.75,16.666667,18.666667
161582,25.2,21.333333,53.8,43.0,24.25,45.666667,17.500000

In [136]:
#playerinfo = pd.concat([playerinfo,averagedskills],axis=1)

In [137]:
playerinfo['weight_to_height']=weight_to_height

In [138]:
playerinfo.drop(columns=playerinfo[modified],inplace=True)
playerinfo.drop(columns=['weight_kg','height_cm'],inplace=True)

In [139]:
meanskill = averagedskills.mean(axis=1)

relskill=pd.DataFrame()
for skill in colus:
    relskill[skill]=averagedskills[skill]>meanskill
relskill=averagedskills[relskill]

lesscols = relskill.isnull().sum(axis=1)
morecols = len(colus)-lesscols
relskill=(relskill.sum(axis=1))/morecols
display(relskill)

0         83.133333
1         84.170000
2         80.406667
3         79.673333
4         64.977778
            ...
161578    47.500000
161579    47.955556
161580    48.429167
161581    48.737500
161582    47.488889
Length: 161583, dtype: float64

In [140]:
playerinfo = pd.concat([playerinfo,relskill],axis=1)

In [141]:
playerinfo.rename(columns={0:'relskill'},inplace=True)

In [142]:
display(playerinfo)

,overall,potential,wage_eur,age,weak_foot,international_reputation,pace,shooting,passing,dribbling,...,rdm,rwb,lb,lcb,cb,rcb,rb,gk,weight_to_height,relskill
0,93.0,95.0,550000.0,27.0,3.0,5.0,93.0,89.0,86.0,96.0,...,65.0,65.0,57.0,48.0,48.0,48.0,57.0,18.0,0.396450,83.133333
1,92.0,92.0,375000.0,29.0,4.0,5.0,93.0,93.0,81.0,91.0,...,66.0,66.0,60.0,55.0,55.0,55.0,60.0,19.0,0.432432,84.170000
2,90.0,90.0,275000.0,30.0,2.0,5.0,93.0,86.0,83.0,92.0,...,67.0,67.0,58.0,49.0,49.0,49.0,58.0,17.0,0.444444,80.406667
3,90.0,90.0,275000.0,32.0,4.0,5.0,76.0,91.0,81.0,86.0,...,68.0,64.0,59.0,58.0,58.0,58.0,59.0,20.0,0.487179,79.673333
4,90.0,90.0,300000.0,28.0,4.0,5.0,-2080.0,-9707.0,-14453.0,-1669.0,...,43.0,39.0,39.0,41.0,41.0,41.0,39.0,90.0,0.476684,64.977778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161578,46.0,61.0,700.0,18.0,3.0,1.0,63.0,48.0,40.0,47.0,...,34.0,39.0,38.0,33.0,33.0,33.0,38.0,16.0,0.405556,47.500000
161579,46.0,58.0,750.0,19.0,3.0,1.0,55.0,25.0,29.0,34.0,...,43.0,45.0,46.0,50.0,50.0,50.0,46.0,17.0,0.441489,47.955556
161580,46.0,58.0,500.0,19.0,2.0,1.0,65.0,36.0,43.0,46.0,...,47.0,49.0,49.0,48.0,48.0,48.0,49.0,16.0,0.403315,48.429167
161581,46.0,70.0,500.0,17.0,3.0,1.0,55.0,50.0,36.0,46.0,...,32.0,36.0,34.0,30.0,30.0,30.0,34.0,17.0,0.388571,48.737500
161582,46.0,63.0,500.0,17.0,3.0,1.0,61.0,22.0,26.0,32.0,...,42.0,41.0,43.0,48.0,48.0,48.0,43.0,15.0,0.388889,47.488889

In [143]:
position_ratings = playerinfo[posrats]
meanrating = position_ratings.mean(axis=1)

relrat=pd.DataFrame()
for rat in posrats:
    relrat[rat]=position_ratings[rat]>meanrating
relrat=position_ratings[relrat]

lesscols = relrat.isnull().sum(axis=1)
morecols = len(posrats)-lesscols
relrat=(relrat.sum(axis=1))/morecols
display(relrat)

0         91.3750
1         89.5000
2         87.7500
3         86.6875
4         54.7500
           ...
161578    47.0000
161579    46.1000
161580    48.0000
161581    45.8125
161582    43.8000
Length: 161583, dtype: float64

In [144]:
playerinfo.drop(columns=posrats,inplace=True)

In [145]:
playerinfo=pd.concat([playerinfo,relrat],axis=1)
playerinfo.rename(columns={0:'relrat'},inplace=True)

In [146]:
display(playerinfo)

,overall,potential,wage_eur,age,weak_foot,international_reputation,pace,shooting,passing,dribbling,defending,physic,weight_to_height,relskill,relrat
0,93.0,95.0,550000.0,27.0,3.0,5.0,93.0,89.0,86.0,96.0,27.0,63.0,0.396450,83.133333,91.3750
1,92.0,92.0,375000.0,29.0,4.0,5.0,93.0,93.0,81.0,91.0,32.0,79.0,0.432432,84.170000,89.5000
2,90.0,90.0,275000.0,30.0,2.0,5.0,93.0,86.0,83.0,92.0,32.0,64.0,0.444444,80.406667,87.7500
3,90.0,90.0,275000.0,32.0,4.0,5.0,76.0,91.0,81.0,86.0,34.0,86.0,0.487179,79.673333,86.6875
4,90.0,90.0,300000.0,28.0,4.0,5.0,-2080.0,-9707.0,-14453.0,-1669.0,-1679.0,-49.0,0.476684,64.977778,54.7500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161578,46.0,61.0,700.0,18.0,3.0,1.0,63.0,48.0,40.0,47.0,24.0,44.0,0.405556,47.500000,47.0000
161579,46.0,58.0,750.0,19.0,3.0,1.0,55.0,25.0,29.0,34.0,48.0,57.0,0.441489,47.955556,46.1000
161580,46.0,58.0,500.0,19.0,2.0,1.0,65.0,36.0,43.0,46.0,43.0,53.0,0.403315,48.429167,48.0000
161581,46.0,70.0,500.0,17.0,3.0,1.0,55.0,50.0,36.0,46.0,20.0,42.0,0.388571,48.737500,45.8125
161582,46.0,63.0,500.0,17.0,3.0,1.0,61.0,22.0,26.0,32.0,45.0,57.0,0.388889,47.488889,43.8000

## Preparing Data for Training

## Training Learners

In [152]:
x = playerinfo.drop(columns='overall')
y = playerinfo['overall']

In [151]:
#splitting into train and test
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest=train_test_split(x,y,test_size=0.2,random_state=42)

import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [153]:
#scaling independent variables
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaled_x=scaler.fit_transform(x)
x = pd.DataFrame(scaled_x, columns = x.columns)

## Training Weak Learners

In [157]:
#Polynomial Regression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

#Create polynomial features
poly = PolynomialFeatures(degree=3)
X_poly_train = poly.fit_transform(Xtrain)
X_poly_test = poly.fit_transform(Xtest) 

#train the model
model = LinearRegression()
model.fit(X_poly_train,Ytrain)
y_pred=model.predict(X_poly_test)

print("Polynomial Regression")
print(f""" MAE = {mean_absolute_error(y_pred,Ytest)},
            RMSE = {np.sqrt(mean_squared_error(y_pred,Ytest))},
            R2 score = {r2_score(y_pred,Ytest)}
            """)

Polynomial Regression
 MAE = 0.7460584128570942,
            RMSE = 1.0086269875990905,
            R2 score = 0.9790203359711434

In [158]:
#Decision Tree
from sklearn.tree import DecisionTreeRegressor

dtree = DecisionTreeRegressor(max_depth=3)
dtree.fit(Xtrain,Ytrain)
y_pred = dtree.predict(Xtest)

print("Decision Tree")
print(f""" MAE = {mean_absolute_error(y_pred,Ytest)},
            RMSE = {np.sqrt(mean_squared_error(y_pred,Ytest))},
            R2 score = {r2_score(y_pred,Ytest)}
            """)

Decision Tree
 MAE = 2.3304278645919965,
            RMSE = 3.1678212071930627,
            R2 score = 0.7453402313970123

In [159]:
#Ridge
from sklearn.linear_model import Ridge

model = Ridge() 
model.fit(Xtrain,Ytrain)
y_pred = model.predict(Xtest)

print("Ridge")
print(f""" MAE = {mean_absolute_error(y_pred,Ytest)},
            RMSE = {np.sqrt(mean_squared_error(y_pred,Ytest))},
            R2 score = {r2_score(y_pred,Ytest)}
            """)

Ridge
 MAE = 1.5588116411985484,
            RMSE = 2.042325489347445,
            R2 score = 0.9072670937103908

## Training Ensemble Methods

In [161]:
import pickle as pkl

In [162]:
#Gradient Boost
from sklearn.ensemble import GradientBoostingRegressor
gb=GradientBoostingRegressor(n_estimators=100,max_depth=3)
gbr = gb.fit(Xtrain, Ytrain)
#pkl.dump(gb, open(r'C:\Users\LENOVO\OneDrive - Ashesi University\Documents\ASHESI\SEMESTERS\3.2\Intro to AI\IntrotoAIAssignments\AIHW2\ClassificationMetrics' + model.__class__.__name__ + '.pkl', 'wb'))
y_pred = gb.predict(Xtest)
print(gb.__class__.__name__, "\nMAE: ", mean_absolute_error(Ytest, y_pred), "\nRMSE:", np.sqrt(mean_squared_error(Ytest, y_pred)),"\nR2:", gbr.score(Xtest,Ytest))

GradientBoostingRegressor
MAE:  0.9376803929826932
RMSE: 1.2488068160500823
R2: 0.9685349642840693

In [163]:
#Random Forest
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(n_estimators=100,max_depth=5)
rfr = rf.fit(Xtrain, Ytrain)
#pkl.dump(rf, open(r'C:\Users\LENOVO\OneDrive - Ashesi University\Documents\ASHESI\SEMESTERS\3.2\Intro to AI\IntrotoAIAssignments\AIHW2\ClassificationMetrics' + rf.__class__.__name__ + '.pkl', 'wb'))
y_pred = rf.predict(Xtest)
print(rf.__class__.__name__, "\nMAE: ", mean_absolute_error(Ytest, y_pred), "\nRMSE:", np.sqrt(mean_squared_error(Ytest, y_pred)),"\nR2:", rfr.score(Xtest,Ytest))

RandomForestRegressor
MAE:  1.6037327462889435
RMSE: 2.2118273460152102
R2: 0.901294772352112

In [164]:
#XGBoost
from xgboost import XGBRegressor

xgb = XGBRegressor(max_depth=5,learning_rate = 0.1)
xgbr = xgb.fit(Xtrain,Ytrain)
#pkl.dump(xgb, open(r'C:\Users\LENOVO\OneDrive - Ashesi University\Documents\ASHESI\SEMESTERS\3.2\Intro to AI\IntrotoAIAssignments\AIHW2\ClassificationMetrics' + rf.__class__.__name__ + '.pkl', 'wb'))

y_pred = xgb.predict(Xtest)
print(xgb.__class__.__name__, "\nMAE: ", mean_absolute_error(Ytest, y_pred), "\nRMSE:", np.sqrt(mean_squared_error(Ytest, y_pred)),"\nR2:", xgbr.score(Xtest,Ytest))

XGBRegressor
MAE:  0.7583911748320048
RMSE: 1.0433849565873923
R2: 0.9780352204019188

## Feature Importance

In [166]:
#Feature Importance for teh best model: XGBRegressor
featurenames = Xtrain.columns
featureimportances = xgb.feature_importances_

In [167]:
importances = pd.DataFrame({'Feature':featurenames,'Importance':featureimportances})
importances.sort_values(by='Importance',ascending=False)

                     Feature  Importance
13                    relrat    0.391563
1                   wage_eur    0.330252
4   international_reputation    0.078736
2                        age    0.049981
0                  potential    0.043045
12                  relskill    0.033285
5                       pace    0.026920
9                  defending    0.020094
6                   shooting    0.009966
7                    passing    0.004532
11          weight_to_height    0.004415
8                  dribbling    0.003602
10                    physic    0.003011
3                  weak_foot    0.000598

In [168]:
topimp = importances[importances.Importance>0.01]
topimp.sort_values(by='Importance',ascending=False)
topfeat = topimp.Feature.tolist()
workingdata=playerinfo[topfeat]
display(workingdata)

,potential,wage_eur,age,international_reputation,pace,defending,relskill,relrat
0,95.0,550000.0,27.0,5.0,93.0,27.0,83.133333,91.3750
1,92.0,375000.0,29.0,5.0,93.0,32.0,84.170000,89.5000
2,90.0,275000.0,30.0,5.0,93.0,32.0,80.406667,87.7500
3,90.0,275000.0,32.0,5.0,76.0,34.0,79.673333,86.6875
4,90.0,300000.0,28.0,5.0,-2080.0,-1679.0,64.977778,54.7500
...,...,...,...,...,...,...,...,...
161578,61.0,700.0,18.0,1.0,63.0,24.0,47.500000,47.0000
161579,58.0,750.0,19.0,1.0,55.0,48.0,47.955556,46.1000
161580,58.0,500.0,19.0,1.0,65.0,43.0,48.429167,48.0000
161581,70.0,500.0,17.0,1.0,55.0,20.0,48.737500,45.8125
161582,63.0,500.0,17.0,1.0,61.0,45.0,47.488889,43.8000

In [257]:
topfeat

['potential',
 'wage_eur',
 'age',
 'international_reputation',
 'pace',
 'defending',
 'relskill',
 'relrat']

In [ ]:
xtest[topfeat]

In [169]:
xw = workingdata
yw = y

In [170]:
#scaling independent variables
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaled_x=scaler.fit_transform(xw)
x = pd.DataFrame(scaled_x, columns = xw.columns)

In [228]:
Xtrain,Xtest,Ytrain,Ytest=train_test_split(xw,yw,test_size=0.3,random_state=42)
X_val,Xtest,Y_val,Ytest=train_test_split(Xtest,Ytest,test_size=0.5,random_state=42)

import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [230]:
X_val

,potential,wage_eur,age,international_reputation,pace,defending,relskill,relrat
151645,73.0,3000.0,25.0,1.0,61.0,68.0,60.316667,65.300000
24138,71.0,6000.0,22.0,1.0,74.0,38.0,60.370000,64.312500
157501,72.0,3000.0,20.0,1.0,65.0,59.0,58.977778,59.400000
113701,66.0,1000.0,32.0,1.0,57.0,67.0,62.541667,62.850000
57444,72.0,9000.0,24.0,1.0,-2665.0,-2128.0,43.688889,33.285714
...,...,...,...,...,...,...,...,...
96906,65.0,3000.0,29.0,1.0,73.0,26.0,63.625000,63.000000
121462,70.0,1000.0,19.0,1.0,60.0,59.0,51.416667,56.400000
47761,78.0,2000.0,18.0,1.0,83.0,31.0,57.025000,56.000000
8062,74.0,2000.0,19.0,1.0,69.0,55.0,57.383333,61.888889
78988,75.0,2000.0,20.0,1.0,73.0,41.0,56.686667,63.312500

## Grid-Search with Cross-Validation (Hyper Parameter Tuning)

In [233]:
from sklearn.model_selection import GridSearchCV, KFold

In [243]:
Cv=KFold(n_splits=3)
eval_set_data = [(Xtrain, Ytrain),(X_val,Y_val)]
xgb = XGBRegressor(n_estimators=100,n_jobs=-1)

PARAMETERS_xgb ={
    "max_depth":[2,5,6,12],
    "learning_rate":[0.01, 0.07, 0.1, 0.15],
    "n_estimators":[200,500,700,1000]}
    #"lambda":[0,3,7,10],
    #"alpha":[0,3,7,10]}

'''fit_parameters  = {
               'eval_metric':"error",
               'eval_set':eval_set_data,
                'early_stopping_rounds':10}'''

model_gs=GridSearchCV(xgb,param_grid=PARAMETERS_xgb, cv=Cv, scoring='neg_mean_squared_error')
model_gs.fit(Xtrain,Ytrain)

print("Best Parameters")
print(model_gs.best_params_)

print("Best Scores")
print(model_gs.best_score_)

print("Best Estimator")
print(model_gs.best_estimator_)

y_pred = model_gs.predict(Xtest)

print(model_gs.__class__.__name__, "\nMAE: ", mean_absolute_error(Ytest, y_pred), "\nRMSE:", np.sqrt(mean_squared_error(Ytest, y_pred)),"\nR2:", model_gs.score(Xtest,Ytest))
pkl.dump(model_gs, open(r'C:\Users\LENOVO\OneDrive - Ashesi University\Documents\ASHESI\SEMESTERS\3.2\Intro to AI\IntrotoAIAssignments\AIHW2\ClassificationMetrics' + model_gs.__class__.__name__ + '.pkl', 'wb'))

Best Parameters
{'learning_rate': 0.07, 'max_depth': 6, 'n_estimators': 1000}
Best Scores
-0.9347608644809634
Best Estimator
XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.07, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=6, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=1000, n_jobs=-1,
             num_parallel_tree=None, random_state=None, ...)
GridSearchCV
MAE:  0.6553028898965467
RMSE: 0.9635758775919433
R2: -0.9284784718770837

In [245]:
ideal_model = model_gs.best_estimator_

In [296]:
pkl.dump(ideal_model, open(r'C:\Users\LENOVO\OneDrive - Ashesi University\Documents\ASHESI\SEMESTERS\3.2\Intro to AI\IntrotoAIAssignments\AIHW2\model' + ideal_model.__class__.__name__ + '.pkl', 'wb'))

## Testing with the testing  data

In [269]:
dataset = pd.read_csv('players_22-1.csv')

C:\Program Files\KMSpico\temp\ipykernel_27668\635433067.py:1: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv('players_22-1.csv')

In [271]:
tneeded = dataset[['overall','potential','wage_eur','age','height_cm','weight_kg','weak_foot',
                      'skill_moves','international_reputation','pace','shooting','passing','dribbling',
                      'defending','physic','attacking_crossing','attacking_finishing','attacking_heading_accuracy',
                      'attacking_short_passing','attacking_volleys','skill_dribbling','skill_curve','skill_fk_accuracy',
                      'skill_long_passing','skill_ball_control','movement_acceleration','movement_sprint_speed',
                      'movement_agility','movement_reactions','movement_balance','power_shot_power','power_jumping',
                      'power_stamina','power_strength','power_long_shots','mentality_positioning','mentality_vision',
                      'mentality_penalties','mentality_composure','defending_marking_awareness','defending_standing_tackle',
                      'defending_sliding_tackle','goalkeeping_diving','goalkeeping_handling','goalkeeping_kicking',
                      'goalkeeping_positioning','goalkeeping_reflexes','goalkeeping_speed',
                      'ls','st','rs','lw','lf','cf','rf','rw','lam','cam','ram','lm','lcm','cm','rcm','rm','lwb',
                      'ldm','cdm','rdm','rwb','lb','lcb','cb','rcb','rb','gk']]

In [273]:
poststats = tneeded.iloc[:,-27:]
posrats = poststats.columns.to_list()

In [275]:
for thiscol in poststats.columns:
        posistat = poststats[thiscol].str.split('+',expand=True)
        posistat.fillna(0,inplace=True)
        posistat = posistat.apply(pd.to_numeric,errors='coerce')
        cols[thiscol] = posistat.sum(axis=1)
    
coldf = pd.DataFrame(cols)

In [276]:
tneeded.drop(columns = tneeded.iloc[:,-27:], inplace = True)
tneeded=pd.concat([tneeded,coldf], axis=1)

C:\Program Files\KMSpico\temp\ipykernel_27668\2860692179.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tneeded.drop(columns = tneeded.iloc[:,-27:], inplace = True)

In [279]:
tplayerdata = preprocessor(tneeded)

C:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\impute\_iterative.py:825: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [281]:
tplayerinfo = tplayerdata.copy()

In [290]:
def featurebuild_train(processed_df):
    playerinfo = processed_df.copy()
    #averaging the skill for the skills column
    attacking = playerinfo.loc[:,playerinfo.columns.str.startswith('attacking')].mean(axis=1).tolist()
    skill =  playerinfo.loc[:,playerinfo.columns.str.startswith('skill')].mean(axis=1).tolist()
    movement =  playerinfo.loc[:,playerinfo.columns.str.startswith('movement')].mean(axis=1).tolist()
    power =  playerinfo.loc[:,playerinfo.columns.str.startswith('power')].mean(axis=1).tolist()
    mentality =  playerinfo.loc[:,playerinfo.columns.str.startswith('mentality')].mean(axis=1).tolist()
    defendingg =  playerinfo.loc[:,playerinfo.columns.str.startswith('defending_')].mean(axis=1).tolist()
    goalkeeping =  playerinfo.loc[:,playerinfo.columns.str.startswith('goalkeeping')].mean(axis=1).tolist()
    
    weight_to_height = playerinfo['weight_kg']/playerinfo['height_cm']
    
    modified = playerinfo.loc[:,playerinfo.columns.str.startswith('attacking')].columns.tolist()+playerinfo.loc[:,playerinfo.columns.str.startswith('skill')].columns.tolist()+playerinfo.loc[:,playerinfo.columns.str.startswith('movement')].columns.tolist()+playerinfo.loc[:,playerinfo.columns.str.startswith('power')].columns.tolist()+playerinfo.loc[:,playerinfo.columns.str.startswith('mentality')].columns.tolist()+playerinfo.loc[:,playerinfo.columns.str.startswith('defending_')].columns.tolist()+playerinfo.loc[:,playerinfo.columns.str.startswith('goalkeeping')].columns.tolist()
    
    skills = [attacking,skill,movement,power,mentality,defendingg,goalkeeping]
    colus = ['attacking','skill','movement','power','mentality','defendingg','goalkeeping']
    averagedskills=pd.DataFrame([attacking,skill,movement,power,mentality,defendingg,goalkeeping],index = colus).T
    
    playerinfo['weight_to_height']=weight_to_height
    
    playerinfo.drop(columns=playerinfo[modified],inplace=True)
    playerinfo.drop(columns=['weight_kg','height_cm'],inplace=True)
    
    meanskill = averagedskills.mean(axis=1)
    relskill=pd.DataFrame()
    for skill in colus:
        relskill[skill]=averagedskills[skill]>meanskill
    relskill=averagedskills[relskill]
    lesscols = relskill.isnull().sum(axis=1)
    morecols = len(colus)-lesscols
    relskill=(relskill.sum(axis=1))/morecols
    playerinfo = pd.concat([playerinfo,relskill],axis=1)
    playerinfo.rename(columns={0:'relskill'},inplace=True)
    
    position_ratings = playerinfo[posrats]
    meanrating = position_ratings.mean(axis=1)
    relrat=pd.DataFrame()
    for rat in posrats:
        relrat[rat]=position_ratings[rat]>meanrating
    relrat=position_ratings[relrat]
    lesscols = relrat.isnull().sum(axis=1)
    morecols = len(posrats)-lesscols
    relrat=(relrat.sum(axis=1))/morecols
    playerinfo.drop(columns=posrats,inplace=True)
    playerinfo=pd.concat([playerinfo,relrat],axis=1)
    playerinfo.rename(columns={0:'relrat'},inplace=True)
    topfeat = ['potential','wage_eur','age','international_reputation','pace','defending','relskill','relrat']
    
    x = playerinfo[topfeat]
    y = playerinfo['overall']
    
    #scaling independent variables
    from sklearn.preprocessing import StandardScaler
    scaler=StandardScaler()
    scaled_x=scaler.fit_transform(x)
    x = pd.DataFrame(scaled_x, columns = x.columns)
    
    #splitting into train and test
    from sklearn.model_selection import train_test_split
    Xtrain,Xtest,Ytrain,Ytest=train_test_split(x,y,test_size=0.2,random_state=42)
    
    import numpy as np
    from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
    
    #XGBoost
    from xgboost import XGBRegressor
    
    xgbt = XGBRegressor(learning_rate = 0.07, max_depth=6, n_estimators=1000)
    xgbrt = xgbt.fit(Xtrain,Ytrain)
    
    y_pred = xgbt.predict(Xtest)
    print(xgbt.__class__.__name__, "\nMAE: ", mean_absolute_error(Ytest, y_pred), "\nRMSE:", np.sqrt(mean_squared_error(Ytest, y_pred)),"\nR2:", xgbrt.score(Xtest,Ytest))

In [292]:
featurebuild_train(tplayerinfo)

XGBRegressor
MAE:  0.655715574593653
RMSE: 0.9401797701350499
R2: 0.9811116802164889